// Tổng hợp service Authorization Management theo hai tuyến request runtime và policy management.
import type { LucideIcon } from 'lucide-react';
import { Database, KeyRound, LayoutPanelTop, LockKeyhole, Navigation, Server } from 'lucide-react';
import { ShowcaseDisclosure } from '../../../components/shared/ShowcaseDisclosure';

interface AuthorizationServiceCardProps { icon: LucideIcon; eyebrow: string; title: string; description: string; }

// Chuẩn hóa card service theo mẫu Recommendation: icon nhận diện, nhãn ngắn và mô tả trách nhiệm cụ thể.
function AuthorizationServiceCard({ icon: Icon, eyebrow, title, description }: AuthorizationServiceCardProps) {
    return <li className="rounded-xl border border-zinc-200 bg-white p-3.5 transition-colors hover:border-zinc-400"><div className="flex items-center gap-2.5"><span className="flex size-7 shrink-0 items-center justify-center text-zinc-700"><Icon aria-hidden="true" className="size-3.5" /></span><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-zinc-700">{eyebrow}</span></div><h4 className="mt-2.5 text-sm font-semibold text-zinc-950">{title}</h4><p className="mt-1 text-xs leading-5 text-zinc-600">{description}</p></li>;
}

// Giữ service overview đồng nhất với Recommendation, nhưng nội dung phản ánh đúng authorization boundary và không dùng nền đen.
export function AuthorizationServicesOverview() {
    return <ShowcaseDisclosure id="authorization-services-overview" number="1.3" title="Các service tham gia" description="Authorization tách nơi phát hành danh tính, nơi enforce request, nơi quản lý policy và nơi sở hữu resource."><div className="space-y-3"><ShowcaseDisclosure id="authorization-request-services" number="1.3.1" title="Luồng kiểm tra request" description="Request đi qua API Gateway, đối chiếu với Keycloak rồi mới được chuyển tới domain service."><ol className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><AuthorizationServiceCard icon={Server} eyebrow="01 · API Gateway" title="api-gateway" description="JwtAuthGuard xác minh JWT bằng public key từ Keycloak JWKS; PermissionsGuard đọc @RequirePermissions và trả 401/403 trước khi proxy." /><AuthorizationServiceCard icon={KeyRound} eyebrow="02 · Identity provider" title="Keycloak" description="Phát hành access token theo realm bin-ecommerce và công bố JWKS endpoint để Gateway kiểm tra chữ ký RS256." /><AuthorizationServiceCard icon={LockKeyhole} eyebrow="03 · Domain services" title="seller-service / product-service" description="Nhận context đã xác thực, rồi tự kiểm tra shop, owner, resource và scope trước khi thực hiện mutation." /></ol></ShowcaseDisclosure><ShowcaseDisclosure id="authorization-policy-services" number="1.3.2" title="Quản lý policy và access profile" description="Auth Service đọc policy từ PostgreSQL, dùng Redis để cache profile và trả quyền hiệu lực cho web app."><ol className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><AuthorizationServiceCard icon={LayoutPanelTop} eyebrow="01 · Policy API" title="auth-service" description="Đọc overview, nhận PATCH role-permission, resolve access profile và ghi audit change." /><AuthorizationServiceCard icon={Database} eyebrow="02 · Source of truth" title="PostgreSQL" description="Lưu user, role, permission, assignment, scope, navigation và permission audit log." /><AuthorizationServiceCard icon={Server} eyebrow="03 · Cache" title="Redis" description="Cache access profile theo userId và permissionVersion; cache chỉ tăng tốc, không thay nguồn policy." /><AuthorizationServiceCard icon={Navigation} eyebrow="04 · Client" title="web · Next.js" description="Gọi profile đã lọc để dựng navigation, default route và màn hình access denied; không tự quyết định quyền." /></ol></ShowcaseDisclosure></div><p className="mt-3 rounded-xl border border-zinc-200 bg-white px-3 py-2.5 text-xs leading-5 text-zinc-600"><strong className="font-semibold text-zinc-900">Ranh giới service:</strong> Keycloak phát hành token; API Gateway xác minh và enforce route; Auth Service quản lý policy/profile; domain service enforce resource; web chỉ trình bày kết quả.</p></ShowcaseDisclosure>;
}
